### ISSUE TITLE
Discrepancy in Event List Length in French / English

### ISSUE THREAD

**Issue by dawadam** [lludol/investing-economic-calendar#2]
Hello,

I've identified a discrepancy in the number of events between the French and English versions.
The French version includes additional events not present in the English version, and vice versa.

Examples today:
French version includes "Conférence de presse de la BCE" at 13:45 and Lagarde's speeches at 15:15 and 16:00.
English version includes "ECB Press Conference" at 13:45.

Is it a bug, or does it come from the investing.com ?

**Comment by lludol** [comment]
Hello,

Yes it's a bug from Investing as you can see with these 2 screenshots:
![screen_1](https://github.com/lludol/investing-economic-calendar/assets/5556262/10d9e541-63e7-4f89-947b-5232e67571ef)
![screen_2](https://github.com/lludol/investing-economic-calendar/assets/5556262/8242f5e8-ed25-4f9f-9e66-a7c1a1342766)
